### ISSUE TITLE
Error when running csctl.py

### ISSUE THREAD

**Issue by GitZurah** [403-Fruit/csctl#7]
I'll just leave you with the console output below as you probably know best whats going on. I installed the script per tutorial, however trying to run it grants me with this issue. Note: I am on Kubuntu 22.04 and as such, modified the csctl.py file to look for 'csgo.sh' instead of 'csgo.exe', though thats the only modification I did.

> ℹ Waiting for CS:GO to start... 
ℹ Trying 127.0.0.1:2121...
✔ Successfully Connected
ℹ Listening for command from console
Traceback (most recent call last):
  File "/home/linda/.tools/csctl/csctl.py", line 99, in <module>
    main()
  File "/home/linda/.tools/csctl/csctl.py", line 74, in main
    tn.read_until(b"exectn ")
  File "/usr/lib/python3.10/telnetlib.py", line 329, in read_until
    return self.read_very_lazy()
  File "/usr/lib/python3.10/telnetlib.py", line 405, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

**Comment by GitZurah** [comment]
randomly started working again

**Comment by GitZurah** [comment]
reopening because sadly the game crashes as soon as i try to execute a script (i used 'echo.csctl' as a test).
note that I wasn't able to execute the script via console output and instead had to resort to writing 'exectn echo' into the actual in-game chat. terminal output following the crash can be seen below.

> ℹ Listening for command from console
Traceback (most recent call last):
  File "/home/linda/.tools/csctl/csctl.py", line 103, in <module>
    main()
  File "/home/linda/.tools/csctl/csctl.py", line 78, in main
    tn.read_until(b"exectn ")
  File "/usr/lib/python3.10/telnetlib.py", line 329, in read_until
    return self.read_very_lazy()
  File "/usr/lib/python3.10/telnetlib.py", line 405, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed
